package com.hqyj.mapper;

import com.hqyj.entity.WxUser;
import com.hqyj.entity.WxUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WxUserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx..wx_user
	 * @mbg.generated  Tue Mar 03 23:59:00 CST 2020
	 */
	long countByExample(WxUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx..wx_user
	 * @mbg.generated  Tue Mar 03 23:59:00 CST 2020
	 */
	int deleteByExample(WxUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx..wx_user
	 * @mbg.generated  Tue Mar 03 23:59:00 CST 2020
	 */
	int deleteByPrimaryKey(Integer Id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx..wx_user
	 * @mbg.generated  Tue Mar 03 23:59:00 CST 2020
	 */
	int insert(WxUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx..wx_user
	 * @mbg.generated  Tue Mar 03 23:59:00 CST 2020
	 */
	int insertSelective(WxUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx..wx_user
	 * @mbg.generated  Tue Mar 03 23:59:00 CST 2020
	 */
	List<WxUser> selectByExample(WxUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx..wx_user
	 * @mbg.generated  Tue Mar 03 23:59:00 CST 2020
	 */
	WxUser selectByPrimaryKey(Integer Id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx..wx_user
	 * @mbg.generated  Tue Mar 03 23:59:00 CST 2020
	 */
	int updateByExampleSelective(@Param("record") WxUser record, @Param("example") WxUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx..wx_user
	 * @mbg.generated  Tue Mar 03 23:59:00 CST 2020
	 */
	int updateByExample(@Param("record") WxUser record, @Param("example") WxUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx..wx_user
	 * @mbg.generated  Tue Mar 03 23:59:00 CST 2020
	 */
	int updateByPrimaryKeySelective(WxUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx..wx_user
	 * @mbg.generated  Tue Mar 03 23:59:00 CST 2020
	 */
	int updateByPrimaryKey(WxUser record);
}