package com.hqyj.entity;

public class WxUser {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx..wx_user.id
	 * @mbg.generated  Tue Mar 03 23:59:00 CST 2020
	 */
	private Integer Id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx..wx_user.wx_openid
	 * @mbg.generated  Tue Mar 03 23:59:00 CST 2020
	 */
	private String wxOpenId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx..wx_user.wx_phone
	 * @mbg.generated  Tue Mar 03 23:59:00 CST 2020
	 */
	private String wxPhone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx..wx_user.identity
	 * @mbg.generated  Tue Mar 03 23:59:00 CST 2020
	 */
	private String identity;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx..wx_user.id
	 * @return  the value of wx..wx_user.id
	 * @mbg.generated  Tue Mar 03 23:59:00 CST 2020
	 */
	public Integer getId() {
		return Id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx..wx_user.id
	 * @param Id  the value for wx..wx_user.id
	 * @mbg.generated  Tue Mar 03 23:59:00 CST 2020
	 */
	public void setId(Integer Id) {
		this.Id = Id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx..wx_user.wx_openid
	 * @return  the value of wx..wx_user.wx_openid
	 * @mbg.generated  Tue Mar 03 23:59:00 CST 2020
	 */
	public String getWxOpenId() {
		return wxOpenId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx..wx_user.wx_openid
	 * @param wxOpenId  the value for wx..wx_user.wx_openid
	 * @mbg.generated  Tue Mar 03 23:59:00 CST 2020
	 */
	public void setWxOpenId(String wxOpenId) {
		this.wxOpenId = wxOpenId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx..wx_user.wx_phone
	 * @return  the value of wx..wx_user.wx_phone
	 * @mbg.generated  Tue Mar 03 23:59:00 CST 2020
	 */
	public String getWxPhone() {
		return wxPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx..wx_user.wx_phone
	 * @param wxPhone  the value for wx..wx_user.wx_phone
	 * @mbg.generated  Tue Mar 03 23:59:00 CST 2020
	 */
	public void setWxPhone(String wxPhone) {
		this.wxPhone = wxPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx..wx_user.identity
	 * @return  the value of wx..wx_user.identity
	 * @mbg.generated  Tue Mar 03 23:59:00 CST 2020
	 */
	public String getIdentity() {
		return identity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx..wx_user.identity
	 * @param identity  the value for wx..wx_user.identity
	 * @mbg.generated  Tue Mar 03 23:59:00 CST 2020
	 */
	public void setIdentity(String identity) {
		this.identity = identity;
	}
}