package com.hqyj.entity;

import java.util.ArrayList;
import java.util.List;

public class WxUserExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table wx..wx_user
	 * @mbg.generated  Tue Mar 03 23:59:00 CST 2020
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table wx..wx_user
	 * @mbg.generated  Tue Mar 03 23:59:00 CST 2020
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table wx..wx_user
	 * @mbg.generated  Tue Mar 03 23:59:00 CST 2020
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx..wx_user
	 * @mbg.generated  Tue Mar 03 23:59:00 CST 2020
	 */
	public WxUserExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx..wx_user
	 * @mbg.generated  Tue Mar 03 23:59:00 CST 2020
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx..wx_user
	 * @mbg.generated  Tue Mar 03 23:59:00 CST 2020
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx..wx_user
	 * @mbg.generated  Tue Mar 03 23:59:00 CST 2020
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx..wx_user
	 * @mbg.generated  Tue Mar 03 23:59:00 CST 2020
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx..wx_user
	 * @mbg.generated  Tue Mar 03 23:59:00 CST 2020
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx..wx_user
	 * @mbg.generated  Tue Mar 03 23:59:00 CST 2020
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx..wx_user
	 * @mbg.generated  Tue Mar 03 23:59:00 CST 2020
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx..wx_user
	 * @mbg.generated  Tue Mar 03 23:59:00 CST 2020
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx..wx_user
	 * @mbg.generated  Tue Mar 03 23:59:00 CST 2020
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx..wx_user
	 * @mbg.generated  Tue Mar 03 23:59:00 CST 2020
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table wx..wx_user
	 * @mbg.generated  Tue Mar 03 23:59:00 CST 2020
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "Id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "Id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "Id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "Id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "Id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "Id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "Id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "Id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "Id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "Id");
			return (Criteria) this;
		}

		public Criteria andWxOpenIdIsNull() {
			addCriterion("wx_openid is null");
			return (Criteria) this;
		}

		public Criteria andWxOpenIdIsNotNull() {
			addCriterion("wx_openid is not null");
			return (Criteria) this;
		}

		public Criteria andWxOpenIdEqualTo(String value) {
			addCriterion("wx_openid =", value, "wxOpenId");
			return (Criteria) this;
		}

		public Criteria andWxOpenIdNotEqualTo(String value) {
			addCriterion("wx_openid <>", value, "wxOpenId");
			return (Criteria) this;
		}

		public Criteria andWxOpenIdGreaterThan(String value) {
			addCriterion("wx_openid >", value, "wxOpenId");
			return (Criteria) this;
		}

		public Criteria andWxOpenIdGreaterThanOrEqualTo(String value) {
			addCriterion("wx_openid >=", value, "wxOpenId");
			return (Criteria) this;
		}

		public Criteria andWxOpenIdLessThan(String value) {
			addCriterion("wx_openid <", value, "wxOpenId");
			return (Criteria) this;
		}

		public Criteria andWxOpenIdLessThanOrEqualTo(String value) {
			addCriterion("wx_openid <=", value, "wxOpenId");
			return (Criteria) this;
		}

		public Criteria andWxOpenIdLike(String value) {
			addCriterion("wx_openid like", value, "wxOpenId");
			return (Criteria) this;
		}

		public Criteria andWxOpenIdNotLike(String value) {
			addCriterion("wx_openid not like", value, "wxOpenId");
			return (Criteria) this;
		}

		public Criteria andWxOpenIdIn(List<String> values) {
			addCriterion("wx_openid in", values, "wxOpenId");
			return (Criteria) this;
		}

		public Criteria andWxOpenIdNotIn(List<String> values) {
			addCriterion("wx_openid not in", values, "wxOpenId");
			return (Criteria) this;
		}

		public Criteria andWxOpenIdBetween(String value1, String value2) {
			addCriterion("wx_openid between", value1, value2, "wxOpenId");
			return (Criteria) this;
		}

		public Criteria andWxOpenIdNotBetween(String value1, String value2) {
			addCriterion("wx_openid not between", value1, value2, "wxOpenId");
			return (Criteria) this;
		}

		public Criteria andWxPhoneIsNull() {
			addCriterion("wx_phone is null");
			return (Criteria) this;
		}

		public Criteria andWxPhoneIsNotNull() {
			addCriterion("wx_phone is not null");
			return (Criteria) this;
		}

		public Criteria andWxPhoneEqualTo(String value) {
			addCriterion("wx_phone =", value, "wxPhone");
			return (Criteria) this;
		}

		public Criteria andWxPhoneNotEqualTo(String value) {
			addCriterion("wx_phone <>", value, "wxPhone");
			return (Criteria) this;
		}

		public Criteria andWxPhoneGreaterThan(String value) {
			addCriterion("wx_phone >", value, "wxPhone");
			return (Criteria) this;
		}

		public Criteria andWxPhoneGreaterThanOrEqualTo(String value) {
			addCriterion("wx_phone >=", value, "wxPhone");
			return (Criteria) this;
		}

		public Criteria andWxPhoneLessThan(String value) {
			addCriterion("wx_phone <", value, "wxPhone");
			return (Criteria) this;
		}

		public Criteria andWxPhoneLessThanOrEqualTo(String value) {
			addCriterion("wx_phone <=", value, "wxPhone");
			return (Criteria) this;
		}

		public Criteria andWxPhoneLike(String value) {
			addCriterion("wx_phone like", value, "wxPhone");
			return (Criteria) this;
		}

		public Criteria andWxPhoneNotLike(String value) {
			addCriterion("wx_phone not like", value, "wxPhone");
			return (Criteria) this;
		}

		public Criteria andWxPhoneIn(List<String> values) {
			addCriterion("wx_phone in", values, "wxPhone");
			return (Criteria) this;
		}

		public Criteria andWxPhoneNotIn(List<String> values) {
			addCriterion("wx_phone not in", values, "wxPhone");
			return (Criteria) this;
		}

		public Criteria andWxPhoneBetween(String value1, String value2) {
			addCriterion("wx_phone between", value1, value2, "wxPhone");
			return (Criteria) this;
		}

		public Criteria andWxPhoneNotBetween(String value1, String value2) {
			addCriterion("wx_phone not between", value1, value2, "wxPhone");
			return (Criteria) this;
		}

		public Criteria andIdentityIsNull() {
			addCriterion("identity is null");
			return (Criteria) this;
		}

		public Criteria andIdentityIsNotNull() {
			addCriterion("identity is not null");
			return (Criteria) this;
		}

		public Criteria andIdentityEqualTo(String value) {
			addCriterion("identity =", value, "identity");
			return (Criteria) this;
		}

		public Criteria andIdentityNotEqualTo(String value) {
			addCriterion("identity <>", value, "identity");
			return (Criteria) this;
		}

		public Criteria andIdentityGreaterThan(String value) {
			addCriterion("identity >", value, "identity");
			return (Criteria) this;
		}

		public Criteria andIdentityGreaterThanOrEqualTo(String value) {
			addCriterion("identity >=", value, "identity");
			return (Criteria) this;
		}

		public Criteria andIdentityLessThan(String value) {
			addCriterion("identity <", value, "identity");
			return (Criteria) this;
		}

		public Criteria andIdentityLessThanOrEqualTo(String value) {
			addCriterion("identity <=", value, "identity");
			return (Criteria) this;
		}

		public Criteria andIdentityLike(String value) {
			addCriterion("identity like", value, "identity");
			return (Criteria) this;
		}

		public Criteria andIdentityNotLike(String value) {
			addCriterion("identity not like", value, "identity");
			return (Criteria) this;
		}

		public Criteria andIdentityIn(List<String> values) {
			addCriterion("identity in", values, "identity");
			return (Criteria) this;
		}

		public Criteria andIdentityNotIn(List<String> values) {
			addCriterion("identity not in", values, "identity");
			return (Criteria) this;
		}

		public Criteria andIdentityBetween(String value1, String value2) {
			addCriterion("identity between", value1, value2, "identity");
			return (Criteria) this;
		}

		public Criteria andIdentityNotBetween(String value1, String value2) {
			addCriterion("identity not between", value1, value2, "identity");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table wx..wx_user
	 * @mbg.generated  Tue Mar 03 23:59:00 CST 2020
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wx..wx_user
     *
     * @mbg.generated do_not_delete_during_merge Wed Feb 19 20:34:16 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}